server:
  port: 9090


spring:

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      routes:
        -  id: wishlist-service
           uri: http://localhost:8082/
           predicates:
             - Path=/api/v1/wishlist/**
           metadata:
              cors
                allowedOrigins: '*'
                allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                allowedHeaders: '*'
                maxAge: 30
        -  id: auth-service
           uri: http://localhost:8085/
           predicates:
             - Path=/api/v1/auth/**
           metadata:
              cors
                allowedOrigins: '*'
                allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                allowedHeaders: '*'
                maxAge: 30
        - id: movie-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/movie/**
          metadata:
              cors
                allowedOrigins: '*'
                allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                allowedHeaders: '*'
                maxAge: 30
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1.0/user/**
          metadata:
              cors
                allowedOrigins: '*'
                allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                allowedHeaders: '*'
                maxAge: 30

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
