server:
  port: 9090


spring:

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        -  id: wishlist-service
           uri: http://ec2-15-229-66-131.sa-east-1.compute.amazonaws.com:8082/
           predicates:
             - Path=/api/v1/wishlist/**
        -  id: auth-service
           uri: http://ec2-15-229-66-131.sa-east-1.compute.amazonaws.com:8085/
           predicates:
             - Path=/api/v1/auth/**
        - id: movie-service
          uri: http://ec2-15-229-66-131.sa-east-1.compute.amazonaws.com:8080/
          predicates:
            - Path=/api/v1/movie/**
        - id: user-service
          uri: http://ec2-15-229-66-131.sa-east-1.compute.amazonaws.com:8081/
          predicates:
            - Path=/api/v1.0/user/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-15-229-66-131.sa-east-1.compute.amazonaws.com:8761/eureka/
    instance:
      hostname: ec2-15-229-66-131.sa-east-1.compute.amazonaws.com
